### PR TITLE
Modified labels for Green line stations

### PR DESCRIPTION
**Pull request by mpeng3**
This is an additional change that goes along with Pull Request #68 "Correct green line".  This request includes changing the labels in the HTML file to show the corrected terminating stations for the B and E branches of the Green Line.

### CODE REVIEW

**Comment by geoffreylitt** [comment]
Thanks, this looks good :+1:  Could you please rebase on top of the latest master branch, and then I'll merge this?

**Comment by davidlago** [comment]
:+1: 

Thanks for the contribution, @mbgdkr!  Just to point out, the file you changed is now `client/templates/landing.html` after the refactoring in #85.

**Comment by mpeng3** [comment]
My changes have been rebased and are ready to be merged!

**Comment by davidlago** [comment]
Thank you, @mbgdkr!

**Pull request merged**
