### PR TITLE
Updated to meteor 1.2.1

### PR DESCRIPTION
**Pull request by patrickgreenwell**
Needed to update to latest version for some changes coming soon.

### CODE REVIEW

**Comment by radhikamalik** [comment]
@davidlago you had mentioned some problems with meteor's Heroku build pack. Does the Meteor version affect it at all?

**Comment by davidlago** [comment]
Yes @radhikamalik... it scares me a bit, we should try to do a test deployment to heroku (setting up a different app) and see if it works.

**Comment by patrickgreenwell** [comment]
I'll try setting up on a separate heroku instance.  @davidlago I'll see if I hit any issues with the current build pack on a seperate heroku instance.  I also see that there is the [Horse buildpack](http://github.com/AdmitHub/meteor-buildpack-horse), I'll try it out and report back.

**Comment by patrickgreenwell** [comment]
~~Did a deploy to my local heroku instance [http://mbta-ninja-staging.herokuapp.com/](http://mbta-ninja-staging.herokuapp.com/) which is working well.  Followed our deployment doc on the readme and didn't really run into any issues. @davidlago Do you remember what issues you hit?~~

Looks like I spoke too soon and didn't clear my cache.  I think it is something with the Restivus package, the new version of that seems to have breaking changes.  I'll update and squash my PR with fixes.

**Comment by patrickgreenwell** [comment]
Ok now it's ready to go, Fixed and squashed my changes into the one commit.  Heroku instance is up and running fine. http://mbta-ninja-staging.herokuapp.com

**Comment by davidlago** [comment]
Thanks Patrick! The problem we faced a couple of months ago prevented the application from starting up on heroku with that build pack. So long as it is up an running in your branch, and it looks like it is, I think we should be all set. Thanks so much!!

**Pull request merged**
