### PR TITLE
Collapsible lines

### PR DESCRIPTION
**Pull request by davidlago**

### CODE REVIEW

**Comment by davidlago** [comment]
image

**Comment by davidlago** [comment]
No scrolling in main page even on an iPhone 4:
image

**Comment by davidlago** [comment]
Thoughts @geoffreylitt & @radhikamalik?

**Comment by JacobEvelyn** [comment]
I like this!

**Comment by deverstalmage** [comment]
I would add in "mdi-navigation-chevron-right" icons to the right of each expanded nb/sb line (to indicate that it will take you to a new view), and left align the whole list (though the alignment thing is maybe just personal preference)

**Comment by JacobEvelyn** [comment]
+1 to both suggestions.

**Comment by deverstalmage** [comment]
this pretty much entirely covers PR #94 btw

**Comment by davidlago** [comment]
Better?

image

**Comment by deverstalmage** [comment]
@davidlago definitely, I would still float (not literally) the arrow to the right – there is a class="secondary-content" that you can wrap around the icon element to achieve this

**Comment by JacobEvelyn** [comment]
I would too. Also, if we're being nitpicky, the arrows should be vertically centered within the line.

**Comment by deverstalmage** [comment]
If the icons don't properly vertically align, which I also had issues with, you can use the secondary-content element and throw a single right angle quote &rsaquo; in there

**Comment by davidlago** [comment]
Sorry @deverstalmage... I just realized about your PR :(

I've incorporated your ideas in this new commit. Now it looks like this:

image

@geoffreylitt, I know you have comments/concerns about this. Please let me know what needs to be fixed, or if this PR is worth "saving" at all... maybe we should start a new one from scratch. Thanks!

**Comment by deverstalmage** [comment]
That looks awesome!

**Comment by geoffreylitt** [comment]
@davidlago @deverstalmage I think the general idea of collapsing nb/sb under a line is good, but don't think this is ready to merge yet. Two things to consider:

1) I'm a fan of #79 by @deverstalmage, and I think the most important improvement we can make on this screen is to give a better at-a-glance view of what's going on with your line, without having to click in. (So if I'm on my morning commute and everything is looking positive/normal, I don't have to click in at all). We should make sure that any collapsible design we come up with here takes that into account. For example, we might not want background colors on the buttons because it makes it harder to use badges or background colors to signify normal/abnormal conditions.

2) I think the visual look of this can be significantly improved. I think the shadowing behind the whole menu block is confusing, and doesn't match Google's material guidelines. I also think the background colors are too heavy and remove too much whitespace, making the page feel less airy.

I think that something more similar to Google's [example of a collapsible menu](http://www.google.com/design/spec/components/list-controls.html#list-controls-types-of-list-controls), perhaps with the train icon on the left colored to match the line, would look cleaner. I'll work on a new branch based on this one incorporating my design ideas to see what you guys think.

**Comment by radhikamalik** [comment]
@davidlago this looks really good; much better than we have now!

I do agree with some of @geoffreylitt's comments about the background colors feeling too heavy. With those and the train icons, the page seems to have a lot going on. I, too am curious to see what combining this new layout with adding back some whitespace would look like.

**Comment by geoffreylitt** [comment]
I just made some style tweaks based on my earlier comment. 

screen shot 2015-03-03 at 9 55 44 pm

**Comment by geoffreylitt** [comment]
Thank you @deverstalmage for getting this one started! I think this is a big improvement. I'm going to close #94 now.

**Pull request merged**
