### PR TITLE
Reduce logo filesize

### PR DESCRIPTION
**Pull request by JacobEvelyn**
Sorry, this is what I meant by #39. It's a mobile-oriented site; the icon shouldn't be 100 KB.

First I shrunk it to double its display size (which is recommended for high-density screens; I notice no change on my Retina screen). Then I ran `optipng` on it which performs lossless compression.

Note that all of the extra blank space around this logo indicates that it can (and should) be reduced further (and further shrinking can happen if #64 goes through). I didn't want to muck about in any spacing though for a first pass.

### CODE REVIEW

**Comment by davidlago** [comment]
:+1: to merge this. Thanks, @JacobEvelyn!

**Comment by JacobEvelyn** [comment]
Thanks for the review!

**Comment by tomleo** [comment]
Are there browsers that this project is committed to support? If support for IE8 isn't required then perhaps an svg logo would make more sense as it will have a smaller file size and scale for larger/higher density displays.

**Comment by JacobEvelyn** [comment]
Great question @tomleo. I'd guess IE8 support isn't a concern given this is targeted at mobile. Would you be able to make an SVG version of the logo?

(Please confirm we don't want IE8 support @radhikamalik @geoffreylitt @davidlago.)

**Comment by tomleo** [comment]
@JacobEvelyn I have not worked with design software for a long time (I'm mostly a backend developer), but I could give it a shot. Who created the original Icon? And what program was used? If Illustrator or Photoshop was used then I believe you can export the image as SVG.

**Comment by geoffreylitt** [comment]
Thanks for this @JacobEvelyn :heart:

@tomleo unfortunately we have a vector asset for this image, so I'm not sure it's worth the effort to convert a bitmap to SVG.

**Comment by JacobEvelyn** [comment]
I don't know much about SVG editing but it feels like it wouldn't be
terrible to build from scratch. On the other hand, a small PNG is probably
fine for our purposes.

**Pull request merged**
